//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassroomReservation()
        {
            this.ClassroomReservationApproval = new HashSet<ClassroomReservationApproval>();
            this.ReservationCourseTable = new HashSet<ReservationCourseTable>();
        }
    
        public int Id { get; set; }
        public string ReservationPersonId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReservationTime { get; set; }
        public Nullable<byte> ReservationState { get; set; }
        public string ReservationPersonName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassroomReservationApproval> ClassroomReservationApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationCourseTable> ReservationCourseTable { get; set; }
    }
}
