//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public int Id { get; set; }
        public string TerminalId { get; set; }
        public string TerminalIp { get; set; }
        public string IdentifyMode { get; set; }
        public string RoomName { get; set; }
        public int Floor { get; set; }
        public int BuildingId { get; set; }
        public string VedioAddress { get; set; }
        public string CardType { get; set; }
        public Nullable<System.TimeSpan> BeginTime1 { get; set; }
        public Nullable<System.TimeSpan> EndTime1 { get; set; }
        public Nullable<System.TimeSpan> BeginTime2 { get; set; }
        public Nullable<System.TimeSpan> EndTime2 { get; set; }
        public Nullable<System.TimeSpan> BeginTime3 { get; set; }
        public Nullable<System.TimeSpan> EndTime3 { get; set; }
    }
}
