//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomReservationApproval
    {
        public int Id { get; set; }
        public string ApprovalPersonId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ApprovalTime { get; set; }
        public Nullable<byte> ApprovalState { get; set; }
        public Nullable<byte> ApprovalLevel { get; set; }
        public int ClassroomReservationId { get; set; }
    
        public virtual ClassroomReservation ClassroomReservation { get; set; }
    }
}
