//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayConfig
    {
        public string TerminalId { get; set; }
        public Nullable<bool> FPD { get; set; }
        public Nullable<bool> ComputerStatus { get; set; }
        public Nullable<bool> Projector { get; set; }
        public Nullable<bool> ProjectionScreen { get; set; }
        public Nullable<bool> Curtain { get; set; }
        public Nullable<bool> Lamp { get; set; }
        public Nullable<bool> Volume { get; set; }
        public Nullable<bool> Record { get; set; }
        public Nullable<bool> LockStatus { get; set; }
        public Nullable<bool> DoorStatus { get; set; }
        public Nullable<bool> LargeScreen { get; set; }
        public Nullable<bool> ACRelay1 { get; set; }
        public Nullable<bool> AirConditioner { get; set; }
    }
}
