//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentLoanLog
    {
        public int ID { get; set; }
        public string SerialName { get; set; }
        public System.DateTime LoanDate { get; set; }
        public Nullable<System.DateTime> PredictReturnDate { get; set; }
        public Nullable<System.DateTime> RealityReturnDate { get; set; }
        public string Borrower { get; set; }
        public string Department { get; set; }
        public string Authorize { get; set; }
        public string Remarks { get; set; }
    }
}
