//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRepairLog
    {
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public string Fault { get; set; }
        public string Proposer { get; set; }
        public System.DateTime DeclarationDate { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public Nullable<double> RepairPrice { get; set; }
        public string RepairComment { get; set; }
        public string ApproverOfficer { get; set; }
        public string Operator { get; set; }
        public string Remarks { get; set; }
    }
}
