//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcCard
    {
        public int Id { get; set; }
        public string HexCode { get; set; }
        public string CardNum { get; set; }
        public string PersonId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Career { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CardType { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string Status { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
