//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysParameter
    {
        public int Id { get; set; }
        public int Ord { get; set; }
        public string ParamKey { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
        public string ParamType { get; set; }
        public string ParamEditor { get; set; }
    }
}
