//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalCurrentInfo
    {
        public string TerminalID { get; set; }
        public Nullable<bool> System { get; set; }
        public Nullable<bool> FPD { get; set; }
        public Nullable<bool> ComputerStatus { get; set; }
        public Nullable<bool> Projector { get; set; }
        public Nullable<bool> ProjectorScreen { get; set; }
        public Nullable<bool> Curtain { get; set; }
        public Nullable<bool> Lamp { get; set; }
        public Nullable<bool> Volume { get; set; }
        public Nullable<bool> Record { get; set; }
        public Nullable<bool> Lock_Status { get; set; }
        public Nullable<bool> Door_Status { get; set; }
        public Nullable<bool> ACRelay1 { get; set; }
        public Nullable<bool> Large_Screen { get; set; }
        public Nullable<bool> AirConitioner { get; set; }
        public Nullable<bool> ProjectionSignal { get; set; }
        public Nullable<bool> ComputerSignal { get; set; }
        public Nullable<bool> LAN1 { get; set; }
        public Nullable<bool> LAN2 { get; set; }
        public Nullable<bool> LAN3 { get; set; }
        public Nullable<bool> LAN4 { get; set; }
        public Nullable<bool> Alarm_In1 { get; set; }
        public Nullable<bool> Alarm_In2 { get; set; }
        public Nullable<bool> Alarm_In3 { get; set; }
        public Nullable<bool> Alarm_In4 { get; set; }
        public Nullable<bool> Alarm_Control { get; set; }
        public Nullable<bool> IN_STATUS1 { get; set; }
        public Nullable<bool> IN_STATUS2 { get; set; }
        public Nullable<bool> IN_STATUS3 { get; set; }
        public string HexCode { get; set; }
        public Nullable<byte> Opereate_Last { get; set; }
    }
}
