//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalInfo
    {
        public int Id { get; set; }
        public string TerminalId { get; set; }
        public Nullable<bool> ACRelay1 { get; set; }
        public Nullable<bool> LockStatus { get; set; }
        public Nullable<byte> LockACT { get; set; }
        public Nullable<bool> ComputerStatus { get; set; }
        public Nullable<byte> ComputerControl { get; set; }
        public Nullable<bool> FPD { get; set; }
        public Nullable<bool> Record { get; set; }
        public Nullable<bool> AirConditioner { get; set; }
        public Nullable<bool> LargeScreen { get; set; }
        public Nullable<bool> DoorControl { get; set; }
        public Nullable<bool> DoorStatus { get; set; }
        public Nullable<bool> Lamp { get; set; }
        public Nullable<bool> Curtain { get; set; }
        public Nullable<bool> System { get; set; }
        public Nullable<bool> Projector { get; set; }
        public Nullable<bool> ProjectionScreen { get; set; }
        public Nullable<byte> ComputerSignal { get; set; }
        public Nullable<byte> Volume { get; set; }
        public Nullable<bool> VolumeMute { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<byte> ProjectionSignal { get; set; }
        public Nullable<bool> DCRelay2 { get; set; }
        public Nullable<bool> OC1 { get; set; }
        public Nullable<bool> OC2 { get; set; }
        public Nullable<byte> Opereate_Last { get; set; }
        public Nullable<bool> LAN1 { get; set; }
        public Nullable<bool> LAN2 { get; set; }
        public Nullable<bool> LAN3 { get; set; }
        public Nullable<bool> LAN4 { get; set; }
        public Nullable<bool> Alarm_Control { get; set; }
        public Nullable<bool> Alarm_In1 { get; set; }
        public Nullable<bool> Alarm_In2 { get; set; }
        public Nullable<bool> Alarm_In3 { get; set; }
        public Nullable<bool> Alarm_In4 { get; set; }
        public Nullable<bool> IN_STATUS1 { get; set; }
        public Nullable<bool> IN_STATUS2 { get; set; }
        public Nullable<bool> IN_STATUS3 { get; set; }
        public string HexCode { get; set; }
    }
}
